pipeline {
    agent any 
        stages {
            stage('Checkout') {
                steps { 
                    git branch: 'main', credentialsId: 'f9e08f77-6385-47e1-902c-7747991d20e6', url: 'https://github.com/gopidevineni/Gopi.git
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
    }
}
